### ISSUE TITLE
Generate output files behind figures in paper

### ISSUE THREAD

**Issue by mwaugh0328** [ganong-noel/ui_calculator#7]
great work guys...

Would it be possible to generate the output behind, e.g., Figure 5 in the BFI working paper, and post it in the repository?

**Comment by ganong123** [comment]
@mwaugh0328 here is Figure 5: [fig5_rep_rate_state.csv.zip](https://github.com/ganong-noel/ui_calculator/files/5016602/fig5_rep_rate_state.csv.zip)

we are going to release a new version of the paper soon which explicitly includes this table. after we release, we will figure out repkit too.

**Comment by mwaugh0328** [comment]
awesome,  I'll watch out for the update,

and quickly, the variable headings are?

**Comment by ganong123** [comment]
`aww` average weekly wage
`rr_fpuc` replacement rate with FPUC
`awba` average weekly benefit amount 
`rr1` replacement rate without FPUC

ignore the last column, which is legacy material

**Comment by mwaugh0328** [comment]
Great, thank you, will be sending you guys something soon showing you what I'm using it for.
